/*
 * Teoria de la Informacion - 2018
 */
package frames;

import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import teoriadelainformaciontpe.BmpHelper;
import teoriadelainformaciontpe.BmpImage;
import teoriadelainformaciontpe.Codificacion;

/**
 *
 * @author ileitao
 * @author ldiez
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
        loadShowImages();
        setTitle("TPE Teoría de la Información - Entrega Nº 1 - 2018");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        copia1 = new javax.swing.JLabel();
        copia2 = new javax.swing.JLabel();
        copia3 = new javax.swing.JLabel();
        copia4 = new javax.swing.JLabel();
        copia5 = new javax.swing.JLabel();
        copia6 = new javax.swing.JLabel();
        copia7 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 524, 680));

        jButton1.setText("Ejercicio 1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exercise1(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 740, -1, -1));

        jButton2.setText("Ejercicio 2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 740, -1, -1));

        jButton3.setText("Ejercicio 3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 740, -1, -1));
        getContentPane().add(copia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 80, 200, 180));
        getContentPane().add(copia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 200, 180));
        getContentPane().add(copia3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 290, 200, 180));
        getContentPane().add(copia4, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 290, 200, 180));
        getContentPane().add(copia5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 490, 200, 180));
        getContentPane().add(copia6, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 490, 200, 180));
        getContentPane().add(copia7, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 490, 200, 180));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesForm/Sin título.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadShowImages() {
        jLabel2.setIcon(new ImageIcon(original.getBmp()));
        jLabel2.setVisible(true);
        BmpImage imagen_1 = new BmpImage(BmpHelper.readBmpImage("Images/Will/Will_1.bmp"), "Copia_1");
        BmpImage imagen_2 = new BmpImage(BmpHelper.readBmpImage("Images/Will/Will_2.bmp"), "Copia_2");
        BmpImage imagen_3 = new BmpImage(BmpHelper.readBmpImage("Images/Will/Will_3.bmp"), "Copia_3");
        BmpImage imagen_4 = new BmpImage(BmpHelper.readBmpImage("Images/Will/Will_4.bmp"), "Copia_4");
        BmpImage imagen_5 = new BmpImage(BmpHelper.readBmpImage("Images/Will/Will_5.bmp"), "Copia_5");
        BmpImage imagen_6 = new BmpImage(BmpHelper.readBmpImage("Images/Will/Will_6.bmp"), "Copia_6");
        BmpImage imagen_7 = new BmpImage(BmpHelper.readBmpImage("Images/Will/Will_7.bmp"), "Copia_7");
        images.add(imagen_1);
        copia1.setIcon(new ImageIcon(imagen_1.getBmp().getScaledInstance(copia1.getWidth(), copia1.getHeight(), imagen_1.getBmp().SCALE_DEFAULT)));
        images.add(imagen_2);
        copia2.setIcon(new ImageIcon(imagen_2.getBmp().getScaledInstance(copia2.getWidth(), copia2.getHeight(), imagen_2.getBmp().SCALE_DEFAULT)));
        images.add(imagen_3);
        copia3.setIcon(new ImageIcon(imagen_3.getBmp().getScaledInstance(copia3.getWidth(), copia3.getHeight(), imagen_3.getBmp().SCALE_DEFAULT)));
        images.add(imagen_4);
        copia4.setIcon(new ImageIcon(imagen_4.getBmp().getScaledInstance(copia4.getWidth(), copia4.getHeight(), imagen_4.getBmp().SCALE_DEFAULT)));
        images.add(imagen_5);
        copia5.setIcon(new ImageIcon(imagen_5.getBmp().getScaledInstance(copia5.getWidth(), copia5.getHeight(), imagen_5.getBmp().SCALE_DEFAULT)));
        images.add(imagen_6);
        copia6.setIcon(new ImageIcon(imagen_6.getBmp().getScaledInstance(copia6.getWidth(), copia6.getHeight(), imagen_6.getBmp().SCALE_DEFAULT)));
        images.add(imagen_7);
        copia7.setIcon(new ImageIcon(imagen_7.getBmp().getScaledInstance(copia7.getWidth(), copia7.getHeight(), imagen_7.getBmp().SCALE_DEFAULT)));
    }

    private void exercise1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exercise1
        // 1) Ordenar imgs utilizando factor de correlación
        new Ejercicio1(this, true, images, original);
    }//GEN-LAST:event_exercise1

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // 2) Generar el histograma a partir de la distribución de tonos y calcular la media el el desvío de cada distribución
        new Ejercicio2(this, false, images, original);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Implementar un algoritmo que permita codificar una imagen mediante el método de Huffman semi-estático y posteriormente reconstruirla 
        //(el archivo comprimido deberá contener la secuencia de bits codificados junto con los datos necesarios para la reconstrucción de la imagen original).
        new Codificacion(original).generateFile();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    private BmpImage original = new BmpImage(BmpHelper.readBmpImage("Images/Will/Will(Original).bmp"), "Original");
    private List<BmpImage> images = new ArrayList<>();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel copia1;
    private javax.swing.JLabel copia2;
    private javax.swing.JLabel copia3;
    private javax.swing.JLabel copia4;
    private javax.swing.JLabel copia5;
    private javax.swing.JLabel copia6;
    private javax.swing.JLabel copia7;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
